# Generated by Django 3.1.5 on 2021-01-12 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Pria', 'pria'), ('Wanita', 'wanita')], max_length=15)),
                ('tgl_lahir', models.DateField()),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Umum', 'umum'), ('Pelajar', 'pelajar'), ('Bekerja', 'bekerja'), ('Mahasiswa', 'mahasiswa')], max_length=50)),
                ('foto_anggota', models.ImageField(null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='data_buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('jenis_buku', models.CharField(choices=[('Cerpen', 'Cerpen'), ('Novel', 'novel'), ('Komputer', 'komputer'), ('Majalah', 'majalah'), ('Manga', 'manga'), ('Komik', 'komik'), ('Sekolah', 'sekolah')], max_length=50)),
                ('penulis', models.CharField(max_length=50)),
                ('tgl_terbit', models.DateField()),
                ('penerbit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='penyumbang_buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyumbang', models.CharField(max_length=100)),
                ('tgl_terima', models.DateField()),
                ('alamat_penyumbang', models.TextField()),
                ('judul_buku', models.CharField(max_length=100)),
                ('jumlah_buku', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('isi', models.CharField(max_length=500)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('thumb', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='suplier_buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_suplier', models.CharField(max_length=100)),
                ('tgl_terima', models.DateField()),
                ('alamat_suplier', models.TextField()),
                ('judul_buku', models.CharField(max_length=100)),
                ('jumlah_buku', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaksi_peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('nama_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.biodata')),
            ],
        ),
        migrations.CreateModel(
            name='kehadiran_anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_absen', models.CharField(choices=[('keluar', 'Keluar'), ('masuk', 'Masuk')], max_length=6)),
                ('waktu', models.DateTimeField()),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.biodata')),
            ],
        ),
        migrations.CreateModel(
            name='data_transaksi_peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=100)),
                ('tgl_buku_dipinjam', models.DateField(auto_now_add=True)),
                ('tgl_buku_dikembalikan', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('denda', models.IntegerField(default=0)),
                ('nama_peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.biodata')),
            ],
        ),
        migrations.CreateModel(
            name='Akun_perpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akun', to=settings.AUTH_USER_MODEL)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodata', to='home.biodata')),
            ],
        ),
    ]
