# Generated by Django 3.1.5 on 2021-01-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Wanita', 'wanita'), ('Pria', 'pria')], max_length=15),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='no_telepon',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='status',
            field=models.CharField(choices=[('Bekerja', 'bekerja'), ('Mahasiswa', 'mahasiswa'), ('Umum', 'umum'), ('Pelajar', 'pelajar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='data_buku',
            name='jenis_buku',
            field=models.CharField(choices=[('Sekolah', 'sekolah'), ('Komik', 'komik'), ('Majalah', 'majalah'), ('Manga', 'manga'), ('Cerpen', 'Cerpen'), ('Novel', 'novel'), ('Komputer', 'komputer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kehadiran_anggota',
            name='jenis_absen',
            field=models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=6),
        ),
    ]
