# Generated by Django 3.1.5 on 2021-01-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210112_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='status',
            field=models.CharField(choices=[('Mahasiswa', 'mahasiswa'), ('Bekerja', 'bekerja'), ('Pelajar', 'pelajar'), ('Umum', 'umum')], max_length=50),
        ),
        migrations.AlterField(
            model_name='data_buku',
            name='jenis_buku',
            field=models.CharField(choices=[('Manga', 'manga'), ('Cerpen', 'Cerpen'), ('Sekolah', 'sekolah'), ('Komputer', 'komputer'), ('Majalah', 'majalah'), ('Komik', 'komik'), ('Novel', 'novel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kehadiran_anggota',
            name='jenis_absen',
            field=models.CharField(choices=[('keluar', 'Keluar'), ('masuk', 'Masuk')], max_length=6),
        ),
    ]
