# Generated by Django 3.1.5 on 2021-01-13 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210114_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_buku',
            name='jumlah_buku',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Pria', 'pria'), ('Wanita', 'wanita')], max_length=15),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='status',
            field=models.CharField(choices=[('Umum', 'umum'), ('Bekerja', 'bekerja'), ('Mahasiswa', 'mahasiswa'), ('Pelajar', 'pelajar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='data_buku',
            name='jenis_buku',
            field=models.CharField(choices=[('Majalah', 'majalah'), ('Manga', 'manga'), ('Sekolah', 'sekolah'), ('Novel', 'novel'), ('Komputer', 'komputer'), ('Komik', 'komik'), ('Cerpen', 'Cerpen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kehadiran_anggota',
            name='jenis_absen',
            field=models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=6),
        ),
    ]
